'use strict';
const cfg=window.JOBMARIO_CONFIG||{};
const client=window.supabase.createClient(cfg.supabaseUrl,cfg.publishableKey);
const $=id=>document.getElementById(id);
const loginBox=$('loginBox'),accountBox=$('accountBox'),leadsPanel=$('leadsPanel');
const authStatus=$('authStatus'),profileStatus=$('profileStatus'),paymentStatus=$('paymentStatus'),leadsStatus=$('leadsStatus'),leadList=$('leadList');
const companyName=$('companyName'),contactName=$('contactName'),companyPhone=$('companyPhone'),companyPlz=$('companyPlz'),companyCity=$('companyCity'),trades=$('trades');
function show(el,msg,error=false){el.textContent=msg;el.classList.remove('hidden');el.style.background=error?'#fff1f0':'#e9fff0';el.style.color=error?'#9b1c1c':'#156b38'}
function esc(v){return String(v??'').replace(/[&<>'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','\"':'&quot;'}[c]))}
async function paymentMessage(){const q=new URLSearchParams(location.search),p=q.get('payment'),sid=q.get('session_id');if(p==='cancelled'){show(paymentStatus,'Zahlung wurde abgebrochen. Es wurde kein Lead freigeschaltet.',true);return}if(p==='success'&&sid){show(paymentStatus,'Zahlung wird geprüft…');const {data,error}=await client.functions.invoke('verify-lead-payment',{body:{session_id:sid}});if(error||!data?.verified){show(paymentStatus,'Zahlung konnte noch nicht bestätigt werden. Bitte Seite erneut laden.',true);return}show(paymentStatus,'Zahlung bestätigt. Kontaktdaten wurden freigeschaltet.');history.replaceState({},'',location.pathname);await loadLeads()}}
async function unlocked(jobId){const {data,error}=await client.rpc('get_unlocked_lead',{p_job_id:jobId});if(error)return null;return Array.isArray(data)&&data.length?data[0]:null}
async function buy(jobId,button){button.disabled=true;button.textContent='Stripe wird geöffnet…';const {data,error}=await client.functions.invoke('create-lead-checkout',{body:{job_id:jobId}});if(error){show(leadsStatus,'Checkout konnte nicht gestartet werden. Bitte erneut versuchen.',true);button.disabled=false;button.textContent='Lead freischalten – 20 €';return}if(data?.already_unlocked){await loadLeads();return}if(data?.url){location.assign(data.url);return}show(leadsStatus,'Checkout konnte nicht gestartet werden.',true);button.disabled=false;button.textContent='Lead freischalten – 20 €'}
async function loadLeads(){leadList.innerHTML='';leadsStatus.classList.add('hidden');const {data:jobs,error}=await client.rpc('list_jobs');if(error){show(leadsStatus,'Aufträge konnten nicht geladen werden.',true);return}if(!jobs?.length){show(leadsStatus,'Aktuell sind noch keine freigegebenen Aufträge vorhanden.');return}for(const job of jobs){const contact=await unlocked(job.id);const card=document.createElement('article');card.className='lead';card.innerHTML=`<div class="lead-top"><div><span class="tag">${esc(job.category)}</span><h3>${esc(job.title)}</h3></div><div class="price">${esc(job.budget)}</div></div><div class="meta">${esc(job.plz)} ${esc(job.city)} · ${esc(job.start_window)}</div>`;if(contact){const box=document.createElement('div');box.className='contact';box.innerHTML=`<strong>Kontakt freigeschaltet</strong><br>${esc(contact.contact_name)}<br>Telefon: ${esc(contact.phone)}<br>E-Mail: ${esc(contact.email)}`;card.appendChild(box)}else{const btn=document.createElement('button');btn.className='orange';btn.type='button';btn.textContent='Lead freischalten – 20 €';btn.addEventListener('click',()=>buy(job.id,btn));card.appendChild(btn);const note=document.createElement('div');note.className='pay-note';note.textContent='Einmalige Zahlung. Kundendaten erst nach bestätigter Zahlung.';card.appendChild(note)}leadList.appendChild(card)}}
async function refresh(){const {data:{session}}=await client.auth.getSession();loginBox.classList.toggle('hidden',!!session);accountBox.classList.toggle('hidden',!session);leadsPanel.classList.toggle('hidden',!session);if(!session)return;const {data,error}=await client.from('contractor_profiles').select('company_name,contact_name,phone,plz,city,trades').eq('user_id',session.user.id).maybeSingle();if(error){show(profileStatus,'Profil konnte nicht geladen werden.',true);return}if(data){companyName.value=data.company_name||'';contactName.value=data.contact_name||'';companyPhone.value=data.phone||'';companyPlz.value=data.plz||'';companyCity.value=data.city||'';trades.value=(data.trades||[]).join(', ');await loadLeads();await paymentMessage()}else{show(leadsStatus,'Speichern Sie zuerst Ihr Firmenprofil, bevor Sie Leads freischalten.')}}
$('loginBtn').addEventListener('click',async()=>{const email=$('authEmail').value.trim();if(!email){show(authStatus,'Bitte E-Mail-Adresse eingeben.',true);return}const redirectTo=new URL('betrieb.html',location.href).href;const {error}=await client.auth.signInWithOtp({email,options:{emailRedirectTo:redirectTo}});show(authStatus,error?'Anmeldung konnte nicht gesendet werden.':'Anmeldelink wurde per E-Mail gesendet.',!!error)});
$('profileForm').addEventListener('submit',async e=>{e.preventDefault();if(!e.currentTarget.reportValidity())return;const {data:{session}}=await client.auth.getSession();if(!session){show(profileStatus,'Bitte erneut anmelden.',true);return}const payload={user_id:session.user.id,company_name:companyName.value.trim(),contact_name:contactName.value.trim(),phone:companyPhone.value.trim(),plz:companyPlz.value.trim(),city:companyCity.value.trim(),trades:trades.value.split(',').map(v=>v.trim()).filter(Boolean),updated_at:new Date().toISOString()};const {error}=await client.from('contractor_profiles').upsert(payload,{onConflict:'user_id'});show(profileStatus,error?'Profil konnte nicht gespeichert werden.':'Firmenprofil gespeichert.',!!error);if(!error)await loadLeads()});
$('logoutBtn').addEventListener('click',async()=>{await client.auth.signOut();await refresh()});
client.auth.onAuthStateChange(()=>setTimeout(refresh,0));refresh();
