'use strict';
const cfg=window.JOBMARIO_CONFIG||{};
const client=window.supabase.createClient(cfg.supabaseUrl,cfg.publishableKey);
const loginBox=document.getElementById('loginBox'),accountBox=document.getElementById('accountBox');
const authStatus=document.getElementById('authStatus'),profileStatus=document.getElementById('profileStatus');
function show(el,msg,error=false){el.textContent=msg;el.classList.remove('hidden');el.style.background=error?'#fff1f0':'#e9fff0';el.style.color=error?'#9b1c1c':'#156b38'}
async function refresh(){const {data:{session}}=await client.auth.getSession();loginBox.classList.toggle('hidden',!!session);accountBox.classList.toggle('hidden',!session);if(!session)return;const {data,error}=await client.from('contractor_profiles').select('company_name,contact_name,phone,plz,city,trades').eq('user_id',session.user.id).maybeSingle();if(error){show(profileStatus,'Profil konnte nicht geladen werden.',true);return}if(data){companyName.value=data.company_name||'';contactName.value=data.contact_name||'';companyPhone.value=data.phone||'';companyPlz.value=data.plz||'';companyCity.value=data.city||'';trades.value=(data.trades||[]).join(', ')}}
document.getElementById('loginBtn').addEventListener('click',async()=>{const email=document.getElementById('authEmail').value.trim();if(!email){show(authStatus,'Bitte E-Mail-Adresse eingeben.',true);return}const redirectTo=new URL('betrieb.html',location.href).href;const {error}=await client.auth.signInWithOtp({email,options:{emailRedirectTo:redirectTo}});show(authStatus,error?'Anmeldung konnte nicht gesendet werden.':'Anmeldelink wurde per E-Mail gesendet.',!!error)});
document.getElementById('profileForm').addEventListener('submit',async e=>{e.preventDefault();if(!e.currentTarget.reportValidity())return;const {data:{session}}=await client.auth.getSession();if(!session){show(profileStatus,'Bitte erneut anmelden.',true);return}const payload={user_id:session.user.id,company_name:companyName.value.trim(),contact_name:contactName.value.trim(),phone:companyPhone.value.trim(),plz:companyPlz.value.trim(),city:companyCity.value.trim(),trades:trades.value.split(',').map(v=>v.trim()).filter(Boolean),updated_at:new Date().toISOString()};const {error}=await client.from('contractor_profiles').upsert(payload,{onConflict:'user_id'});show(profileStatus,error?'Profil konnte nicht gespeichert werden.':'Firmenprofil gespeichert.',!!error)});
document.getElementById('logoutBtn').addEventListener('click',async()=>{await client.auth.signOut();await refresh()});client.auth.onAuthStateChange(()=>setTimeout(refresh,0));refresh();